### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by miyamot0** [milsto/differential-evolution#1]
Greetings, I really like the implementation here. I'd like to Port some of these methods into a project of mine. Do you have a license in mind? I'm hoping to try to include something like this in a GPL project of mine.

**Comment by milsto** [comment]
Hi @miyamot0, thanks for interest in this project. I am going to think about license and add it soon, but I can say that it will most certainly be compatible with your GPL project.

**Comment by miyamot0** [comment]
Bump. I'd like to more directly cite your work as part of a developing GPL project. Have you decided on a license?

**Comment by milsto** [comment]
The license has been added and its MIT.

Sorry for waiting.

**Comment by milsto** [comment]
Also, thanks again for finding this project useful. Pleas, just out of interest, throw me a link to the project where you will be using it.

**Comment by miyamot0** [comment]
Sure! It's used in two projects as a backup, derivative-free optimization strategy.

[Discounting Model Selector](https://github.com/miyamot0/ModelSelectorQt)
[Behavioral Economic Demand calculator](https://github.com/miyamot0/DemandCalculatorQT)

I also ported something similar to javascript, using your code as a reference, but haven't gotten around to releasing it all yet.
